.TH "pa-notify" "1" "25 July 2021" "pa-notify(1)" "User manual"

.SH NAME

pa-notify \(em PulseAudio volume notification

.SH SYNOPSIS

.PP
\fBpa-notify\fR [\fBOPTIONS\fR]

.SH DESCRIPTION

.PP
\fBpa-notify\fR is PulseAudio volume notification. It get information from PulseAudio using libpulse and send notification using libnotify. 

.SH OPTIONS

.IP "\fB-h\fR, \fB--help\fR" 5
Show help options
.IP "\fB-d\fR, \fB--debug\fR" 5
Enable debug information.
.SH EXAMPLES

.EX

.TP
batify
.EE

